# Dockerfile for building server image

# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Install the dependencies
RUN apt-get update && \
    apt-get install -y python3-dev zlib1g-dev gcc make libmariadb-dev && \
    pip install --upgrade pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy the all files
COPY . /app

# Install Python dependencies
RUN pip install -r requirements.txt

# Expose the necessary port to use by user frontend
# EXPOSE 5000

# Set the default command
CMD ["python", "-m", "api.app"]
